Repository haikuports/haikuports, pull requests merged in 2018-09, with the labels that each got.

#3004 Mesa cleanup
  sys-libs/mesa/mesa-10.0.1.recipe
  sys-libs/mesa/mesa-10.0.2.recipe
  sys-libs/mesa/mesa-10.1.0.recipe
  sys-libs/mesa/mesa-10.1.1.recipe
  sys-libs/mesa/mesa-10.2.9.recipe
  sys-libs/mesa/mesa-10.3.7.recipe
  sys-libs/mesa/mesa-10.4.7.recipe
  sys-libs/mesa/mesa-10.5.2.recipe
  sys-libs/mesa/mesa-11.0.1.recipe
  sys-libs/mesa/mesa-11.2.2.recipe
  sys-libs/mesa/mesa-12.0.4.recipe
  sys-libs/mesa/mesa-13.0.4.recipe
  sys-libs/mesa/mesa-17.0.6.recipe
  sys-libs/mesa/mesa-17.1.4.recipe
  sys-libs/mesa/mesa-9.1.1.recipe
  sys-libs/mesa/patches/mesa-10.0.1.patchset
  sys-libs/mesa/patches/mesa-10.0.2.patchset
  sys-libs/mesa/patches/mesa-10.1.0.patchset
  sys-libs/mesa/patches/mesa-10.1.1.patchset
  sys-libs/mesa/patches/mesa-10.2.9.patchset
  sys-libs/mesa/patches/mesa-10.4.7.patchset
  sys-libs/mesa/patches/mesa-10.5.2.patchset
  sys-libs/mesa/patches/mesa-11.0.1.patchset
  sys-libs/mesa/patches/mesa-11.2.2.patchset
  sys-libs/mesa/patches/mesa-12.0.4.patchset
  sys-libs/mesa/patches/mesa-13.0.4.patchset
  sys-libs/mesa/patches/mesa-9.0.1.patch
  sys-libs/mesa/patches/mesa-9.0.2.patch
  sys-libs/mesa/patches/mesa-9.0.patch
  sys-libs/mesa/patches/mesa-9.1.1.patch
Labels: feedback-needed

#2728 tar: bump to 1.30.
  app-arch/tar/patches/tar-1.29.patchset
  app-arch/tar/patches/tar-1.30-gcc2.patchset
  app-arch/tar/tar-1.30.recipe
Labels: help-wanted, wip-no-merge

#586 cylindrix, update recipe so it builds and installs the data
  games-action/cylindrix/cylindrix-1.0.recipe
Labels: help-wanted, task, wip-no-merge

#2115 MatchColumns, new recipe
  haiku-games/matching-columns/matching_columns-0.1.0~git.recipe
Labels: help-wanted
