Repository haikuports/haikuports, pull requests merged in 2018-10, with the labels that each got.

#3191 Fuel - new recipe
  dev-vcs/fuel/additional-files/fuel.rdef.in
  dev-vcs/fuel/fuel-1.0.1.recipe
  dev-vcs/fuel/patches/fuel-1.0.1.patchset
Labels: help-wanted, needs testing and review

#3197 fre:ac: New recipe for fre:ac 1.1 alpha.
  media-sound/freac/additional-files/freac.rdef.in
  media-sound/freac/freac-1.1~alpha20180913.recipe
  media-sound/freac/patches/freac-1.1~alpha20180913.patchset
Labels: wip-no-merge

#3227 net-libs/libssh: update to 0.8.4
  net-libs/libssh/libssh-0.8.4.recipe
  net-libs/libssh/patches/libssh-0.8.4.patchset
Labels: wip-no-merge

#3271 html5-parser: new recipe
  dev-python/html5-parser/html5_parser-0.4.5.recipe
Labels: wip-no-merge

#3299 zstd: bump to 1.3.7.
  app-arch/zstd/patches/zstd-1.3.5-gcc2.patchset
  app-arch/zstd/patches/zstd-1.3.5.patchset
  app-arch/zstd/patches/zstd-1.3.7-gcc2.patchset
  app-arch/zstd/patches/zstd-1.3.7.patchset
  app-arch/zstd/zstd-1.3.7.recipe
Labels: help-wanted, needs testing and review, wip-no-merge
